version: "3.8"

services:
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=kevinahumada.com.ar
      - MYSQL_DATABASE=kevinahu_universidad
      - MYSQL_USER=kevinahu_franci
      - MYSQL_PASSWORD=2BhNwieRJdRe
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    expose:
      - 80
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql